name = "puzzle-game-server"
main = "src/index.js"  # この行がエントリーポイントを指定している
compatibility_date = "2023-05-18"

[vars]
SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL"
SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"
