name = "puzzle-game-server"
main = "src/index.js"  # エントリーポイントを指定（Cloudflare Workersでのメインファイル）
compatibility_date = "2023-05-18"

# 環境変数を設定
[vars]
SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL"
SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"

# クラウドフレアPagesではなく、Worker向けのビルドとデプロイ設定が必要です
[build]
command = "npm run build"
upload = { 
  format = "service-worker", 
  dir = "./dist"  # ビルド後のJavaScriptファイルのパス
}
